apiVersion: apps/v1
kind: Deployment
metadata:
  name: food-delivery-backend
  labels:
    app: food-delivery-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: food-delivery-backend
  template:
    metadata:
      labels:
        app: food-delivery-backend
    spec:
      containers:
        - name: food-delivery-backend
          image: 803133979340.dkr.ecr.ap-south-1.amazonaws.com/food-delivery-backend:latest
          ports:
            - containerPort: 4000
          env:
            - name: NODE_ENV
              value: production
            - name: MONGO_URI          # <--- FIXED!!
              value: "mongodb://mongo-service:27017/fooddb"
          imagePullPolicy: Always
