apiVersion: apps/v1
kind: Deployment
metadata:
  name: food-delivery-backend
  labels:
    app: food-delivery-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: food-delivery-backend
  template:
    metadata:
      labels:
        app: food-delivery-backend
    spec:
      containers:
        - name: food-delivery-backend
          image: jeevankumar01/food-delivery-backend:latest
          ports:
            - containerPort: 4000
          env:
            - name: NODE_ENV
              value: production
            - name: MONGO_URL
              value: "mongodb://mongo-service:27017/fooddb"  # <-- Point to MongoDB service
          imagePullPolicy: Always
      imagePullSecrets:
        - name: dockerhub-secret
