apiVersion: v1
kind: Service
metadata:
  name: food-delivery-backend-service
spec:
  type: LoadBalancer
  selector:
    app: food-delivery-backend
  ports:
    - port: 4000          # external port
      targetPort: 4000     # container port
