apiVersion: v1
kind: Service
metadata:
  name: food-delivery-backend-service
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-healthcheck-protocol: TCP
    service.beta.kubernetes.io/aws-load-balancer-healthcheck-port: "4000"
spec:
  type: LoadBalancer
  selector:
    app: food-delivery-backend
  ports:
    - port: 4000
      targetPort: 4000
      protocol: TCP
